### ISSUE TITLE
Training the model on custom dataset

### ISSUE THREAD

**Issue by eashangill** [apostaremczak/iris-recognition#1]
Can you give us the training code for colab so that we can train it on other users in ubiris dataset or on any other dataset we want to?

**Comment by apostaremczak** [comment]
Hey, the training fuction is available in [model/train.py](https://github.com/apostaremczak/iris-recognition/blob/master/model/train.py), my Colab notebook only imported this module and used train.run :)

**Comment by eashangill** [comment]
I am really bad at it. Can you please tell me how to train it using my
custom dataset like steps.
