### ISSUE TITLE
How to train a model

### ISSUE THREAD

**Issue by adarsh-dikhit** [apostaremczak/iris-recognition#3]
Train_config is not working.

**Comment by apostaremczak** [comment]
Hi,

Could you please provide more details? What error are you getting? What are your Python environment settings? In particular, do you use the same versions of all the libraries? This project has been written quite a long time ago, so I can't ensure it's still working with the newest library versions.

Where did you put your train data? Is it also [UBIRIS.v1 database](http://iris.di.ubi.pt/ubiris1.html)? I haven't tested it with any other database.
